server:
  port: 8081

spring:
  application:
    name: fraud
  datasource:
    username: 'msuser'
    url: jdbc:postgresql://localhost:5432/fraud
    password: 'mssecret'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  cloud:
    config:
      import-check:
        enabled: false
    compatibility-verifier:
      enabled: false
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true
